backend:
  name: git-gateway
  branch: main

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    format: "json"
    extension: "json"
    fields:
      - { label: "Tiêu đề", name: "title", widget: "string" }
      - { label: "Ngày", name: "date", widget: "datetime" }
      - { label: "Tác giả", name: "author", widget: "string" }
      - { label: "Hình ảnh", name: "image", widget: "image" }
      - { label: "Mô tả", name: "summary", widget: "text" }
      - { label: "Nội dung", name: "content", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }